version: '3.5'
services:
  web:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - symfony
  app:
    build:
      context: ./
      dockerfile: ./php/Dockerfile
    volumes: 
      - ./app/:/var/www/html/
    networks:
      - symfony

  mailer:
    image: schickling/mailcatcher
    ports: ["1025", "1080"]
    networks:
      - symfony
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'bexio'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql3
    networks:
      - symfony
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8001:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - symfony
# Names our volume
volumes:
  my-db:

networks:
  symfony:
