version: '3.5'
services:
  mailer:
    image: schickling/mailcatcher
    ports: ["1025", "1080"]
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'bexio'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql3
# Names our volume
volumes:
  my-db:
